# Generated for the Nimesh Rai portfolio app.
import django.core.validators
import django.db.models.deletion
import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="achievements/")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["order", "-year"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField(validators=[portfolio.validators.validate_contact_message_length])),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("institution", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=200)),
                ("field", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("relevant_coursework", models.JSONField(blank=True, default=list)),
                ("projects", models.JSONField(blank=True, default=list)),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["order", "-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("technologies", models.JSONField(blank=True, default=list, help_text='List of technologies, e.g. ["Django", "PostgreSQL"]')),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experience",
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("intro", models.TextField(blank=True, help_text="Hero / intro copy")),
                ("who_i_am", models.TextField(blank=True)),
                ("what_i_build", models.TextField(blank=True)),
                ("what_i_know", models.TextField(blank=True)),
                ("what_im_learning", models.TextField(blank=True)),
                ("where_im_going", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="profile/")),
                ("location", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("category", models.CharField(choices=[("ALL", "All"), ("PYTHON", "Python"), ("DJANGO", "Django"), ("AI", "AI"), ("DATA", "Data"), ("WEB", "Web"), ("DATABASE", "Database"), ("AUTOMATION", "Automation"), ("OTHER", "Other")], default="OTHER", max_length=20)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("problem", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("features", models.JSONField(blank=True, default=list, help_text='List of feature strings, e.g. ["Project CRUD", "REST API"]')),
                ("architecture", models.TextField(blank=True)),
                ("database", models.TextField(blank=True)),
                ("challenges", models.TextField(blank=True)),
                ("learning", models.TextField(blank=True)),
                ("tech_stack", models.JSONField(blank=True, default=list, help_text='List of technologies, e.g. ["Python", "Django"]')),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("featured_image", models.ImageField(blank=True, null=True, upload_to="projects/")),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("ACTIVE", "Active Development"), ("COMPLETED", "Completed"), ("IN_PROGRESS", "In Progress"), ("MAINTAINED", "Maintained"), ("ARCHIVED", "Archived")], default="ACTIVE", max_length=30)),
                ("completion_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="Resume", max_length=200)),
                ("file", models.FileField(blank=True, null=True, upload_to="resumes/")),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site_name", models.CharField(default="Nimesh Rai", max_length=120)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="site/")),
                ("enable_spider_sense", models.BooleanField(default=True)),
                ("enable_easter_eggs", models.BooleanField(default=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("footer_text", models.CharField(blank=True, max_length=255)),
                ("github_username", models.CharField(blank=True, max_length=100)),
                ("linkedin_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.CharField(max_length=80)),
                ("url", models.URLField()),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
                "ordering": ["order", "platform"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="portfolio.project")),
            ],
            options={
                "verbose_name": "Project Image",
                "verbose_name_plural": "Project Images",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("proficiency", models.PositiveSmallIntegerField(default=70, help_text="Proficiency 1-100", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100), portfolio.validators.validate_proficiency])),
                ("icon", models.CharField(blank=True, help_text="Optional icon name / CSS class / asset key", max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("spider_sense_highlight", models.BooleanField(default=False, help_text="Highlight in Spider-Sense HUD")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skills", to="portfolio.skillcategory")),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["order", "name"],
            },
        ),
    ]
